version: 2
jobs:
  build:
    working_directory: ~/jonatanblue/rundeck-test-server
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/python:3-stretch-browsers-legacy
    steps:
    # Check out the code
    - checkout
    # Install dependencies
    - run: sudo apt install -y ansible python-boto
    # Deploy test instance and run tests
    - run: ansible-playbook -i "localhost," deploy.yml -e aws_region=${AWS_REGION?} -e ec2_key_name=${KEY_NAME?} -e ec2_security_group_id=${SECURITY_GROUP_ID?} -e ec2_subnet_id=${SUBNET_ID?} -e ec2_vpc_id=${VPC_ID?}
